#ifndef GEL_INTERNAL_CONF_H_INCLUDED
#define GEL_INTERNAL_CONF_H_INCLUDED


#if defined(CONFIG_GEL_PARAMETER_CONFIGURATION_HEADER) && !defined(GEL_PARAMETER_CONFIGURATION_HEADER)
#define GEL_PARAMETER_CONFIGURATION_HEADER CONFIG_GEL_PARAMETER_CONFIGURATION_HEADER
#endif


#if defined(CONFIG_GEL_PAGEMANAGER_CONFIGURATION_HEADER) && !defined(GEL_PAGEMANAGER_CONFIGURATION_HEADER)
#define GEL_PAGEMANAGER_CONFIGURATION_HEADER CONFIG_GEL_PAGEMANAGER_CONFIGURATION_HEADER
#endif


#endif